apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
  namespace: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      containers:
        - name: agent
          image: jenkins-agent:latest
          command: ["sleep", "infinity"]
